TODO MASTER (Wed Dec 14 02:05:13 2016)                  *Generated by github.com/eclectickmedia/todotracker*
--------


./Plot.py

--------

149:                if not self.nofile:  # TODO needs use case testing.


./tests.py

--------

175:    # TODO Test `Plot._Plot.show_plot`
