TODO MASTER (Tue Dec 20 19:59:49 2016)                  *Generated by github.com/eclectickmedia/todotracker*
--------


./main.py

--------

64:# TODO Test no file generation.


./tests.py

--------

180:    # TODO Test `Plot._Plot.show_plot`
