TODO MASTER (Mon Dec 12 05:05:17 2016)                  *Generated by github.com/eclectickmedia/todotracker*
--------


./Plot.py

--------

149:                if not self.nofile:  # TODO needs use case testing.


./tests.py

--------

149:    # TODO Test `Plot._Plot.show_plot`
